language: python
python:
  - "3.6"

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - bash install.sh


before_script:
  - conda list
  - bash download-data.sh

script:
  - ls -lh data/
  - dsc --version
  - dsc mouthwash.dsc -h
  - dsc mouthwash.dsc
