language: python
python:
  - "3.6"

install:
  # Install Miniconda3
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  # Configure conda
  - conda config --set always_yes yes
  - conda config --set changeps1 no
  - conda config --add channels jdblischak
  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  # Install conda packages
  - conda install
      --file requirements/sos-conda
      --file requirements/dsc-conda
      --file requirements/mouthwash-conda
      --file requirements/dscrutils-conda
  # Install Python packages from PyPI
  - pip install --no-deps
      -r requirements/sos-pip
      -r requirements/dsc-pip
  # Install R package dscrutils from GitHub
  - travis_retry bash install.sh

before_script:
  - conda list
  - bash download-data.sh

script:
  - ls -lh data/
  - dsc --version
  - dsc mouthwash.dsc -h
  - dsc mouthwash.dsc
