language: python
python:
  - "3.6"
install:
  # Install Miniconda3
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  # Configure conda
  - conda config --set always_yes yes
  - conda config --set changeps1 no
  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  # Install conda packages
  - conda install
      --file requirements/sos-conda
      --file requirements/dsc-conda
      --file requirements/mouthwash-conda
  # Install Python packages from PyPI
  - pip install --no-deps
      -r requirements/sos-pip
      -r requirements/dsc-pip
  # Install R packages from CRAN and GitHub
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends
      g++ gcc gfortran
  - Rscript install.R

script:
  - bash download-data.sh
  - ls -lh data/
