version: 2
jobs:
  build:
    working_directory: /dsc-mouthwash
    docker:
      - image: continuumio/miniconda3:4.3.27p0
    steps:
      - checkout
      - run:
          name: Installation
          command: |
            bash install.sh
            conda list
      - run:
          name: Download data
          command: |
            bash download-data.sh
            ls -lh data/
      - run:
          name: Run DSC
          command: |
            dsc --version
            dsc mouthwash.dsc -h
            dsc mouthwash.dsc
      - store_artifacts:
          path: mouthwash/
      - store_artifacts:
          path: mouthwash.html
